### ISSUE TITLE
As Animal Quarantine I would like to notify Pet Owners their pet is ready for pick-up via text message.

### ISSUE THREAD

**Issue by JJ-Foust** [HACC2021/MVP#3]

**Comment by JJ-Foust** [comment]
Digital Waitlist needs to be sorted by MicroChip number since that is what the existing system sorts pets by.

**Comment by JJ-Foust** [comment]
Data is collected via google form. Then phone number is converted to email address based on service carrier. Then front desk personnel can send email to Pet owners phone. 

This is done so as to now have to incur SMS rates and making it a low cost option.

**Comment by tyliec** [comment]
SMS notifications are now available using Twilio
