### ISSUE TITLE
Open source requirement: permission notice must be included

### ISSUE THREAD

**Issue by judyn808** [HACC2021/MVP#34]
The source code for all submissions shall be published in a public repository on GitHub.com in accordance with the Section 2. above and **must include an open source code license**.  We recommend you use the GNU General Public License or the MIT License for open source software.  For other options, please see https://choosealicense.com.

A copyright notice and this permission notice shall be included in all copies or substantial portions of the Software; **the Software is provided “as is,” without warranty of any kind, express or implied, including but not limited to the warranties of merchantability, fitness for a particular purpose and non-infringement. In no event shall the authors or copyright holders be liable for any claim, damages or other liability, whether in an action of contract, tort or otherwise, arising from, out of or in connection with the software or the use or other dealings in the software.**

**Comment by tyliec** [comment]
We currently have a `LICENSE` file located here: https://github.com/HACC2021/MVP/blob/main/LICENSE

It is the "GNU General Public License v3.0"
